pip install torch
pip install numpy
pip install timesfm
pip install jax
pip install einops
pip install matplotlib
pip install patool
pip install reformer-pytorch
pip install scikit-learn
pip install scipy
pip install sktime
pip install sympy
pip install tqdm
pip install transformers
pip install SentencePiece